// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVckPIxhoZ2RcU3Ojg8ia5qzTHUVYXGXw',
    appId: '1:797242402596:web:70dd73c068a2d9771075b1',
    messagingSenderId: '797242402596',
    projectId: 'fir-upload-89331',
    authDomain: 'fir-upload-89331.firebaseapp.com',
    databaseURL: 'https://fir-upload-89331-default-rtdb.firebaseio.com',
    storageBucket: 'fir-upload-89331.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPmA-kBK9lMVnmJWy_UyHUsZcLituDyT0',
    appId: '1:797242402596:android:d10066db278b962d1075b1',
    messagingSenderId: '797242402596',
    projectId: 'fir-upload-89331',
    databaseURL: 'https://fir-upload-89331-default-rtdb.firebaseio.com',
    storageBucket: 'fir-upload-89331.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtJKGoEtf6xlLGfvmy8-MypkrzlfZLitE',
    appId: '1:797242402596:ios:aa50abeb5e3236231075b1',
    messagingSenderId: '797242402596',
    projectId: 'fir-upload-89331',
    databaseURL: 'https://fir-upload-89331-default-rtdb.firebaseio.com',
    storageBucket: 'fir-upload-89331.appspot.com',
    iosBundleId: 'com.example.storeImage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtJKGoEtf6xlLGfvmy8-MypkrzlfZLitE',
    appId: '1:797242402596:ios:d2dabde5d37fffac1075b1',
    messagingSenderId: '797242402596',
    projectId: 'fir-upload-89331',
    databaseURL: 'https://fir-upload-89331-default-rtdb.firebaseio.com',
    storageBucket: 'fir-upload-89331.appspot.com',
    iosBundleId: 'com.example.storeImage.RunnerTests',
  );
}
